config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'persons/profile', as: 'user_root' 

  get 'admins', to: 'admins#index'

  get 'teams/search', to: 'teams#search'
  get 'tournaments/search', to: 'tournaments#search'
  get 'users/search', to: 'users#search'

  resources :users, :tournaments, :teams, :matches, :rounds, :votings

  resources :tournaments do
    resources :rounds
  end

  resources :rounds do
    resources :matches
  end

end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :tournament
  has_many :teams
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def create
    @round=Round.new round_params
    if @round.save
      flash[:notice] = ""
      redirect_to @round
    else
      flash[:notice] = "Something went wrong, try again"
      render "new"
    end
  end

  def show
    @round = Round.find_by id: params[:id]
    if @round.nil?
      flash[:notice] = "Round not found"
      render "index"
    end
    flash[:tournament_name] = Tournament.find_by(id: @round.tournament_id).name
  end

  def update
    #@round=Round.update(params[:id],:name => params[:round][:name], 
    #  :round_type => params[:round][:round_type], :order => params[:round][:order])
    @round = Round.update params[:id], round_params
    if @round.save
      flash[:notice] = "Changes saved"
      redirect_to @round
    else
      flash[:notice] = "Something went wrong, try again"
      render "edit"
    end
  end

  def round_params
    params.require(:round).permit(:tournament_id, :name, :round_type, :order)
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/edit.html.erb
<h1>Rounds#edit</h1>
<p>Find me in app/views/rounds/edit.html.erb</p>

<%= flash[:notice] %>
<% @round = Round.find_by id: params[:id] %>

<%= form_tag "/rounds/#{params[:id]}", method: 'put' do %>
	<%= content_tag :div, :class => 'form-group' do %>
		<%= label :round,:name %>
		<%= text_field :round, :name %>
	<% end %>
	<%= content_tag :div, :class => 'form-group' do %>
		<%= label :round,:round_type %>
		<%= text_field :round, :round_type %>
	<% end %>
	<%= content_tag :div, :class => 'form-group' do %>
		<%= label :round,:order %>
		<%= text_field :round, :order %>
	<% end %>
	<%= submit_tag "Save changes", class: 'btn btn-default' %>
<% end %>

<%= link_to 'Add match', new_round_match_path(params[:id]), class: "btn btn-default" %>

app/views/rounds/index.html.erb
<h1>Rounds#index</h1>
<p>Find me in app/views/rounds/index.html.erb</p>

<%= flash[:notice] %>
<% flash[:notice] = "" %>

app/views/rounds/new.html.erb
<h1>Rounds#new</h1>
<p>Find me in app/views/rounds/new.html.erb</p>

<%= flash[:notice] %>

<%= form_tag :rounds, method: 'post' do %>
	<%= text_field :round,:tournament_id, :type => 'hidden', :value => params[:tournament_id] %>
	<%= content_tag :div, :class => 'form-group' do %>
		<%= label :round,:name %>
		<%= text_field :round, :name %>
	<% end %>
	<%= content_tag :div, :class => 'form-group' do %>
		<%= label :round, :round_type %>
		<%= text_field :round, :round_type %>
	<% end %>
	<%= content_tag :div, :class => 'form-group' do %>
		<%= label :round, :order %>
		<%= text_field :round, :order %>
	<% end %>
	<%= submit_tag "Add new round" %>
<% end %>

app/views/rounds/show.html.erb
<h1>Rounds#show</h1>
<p>Find me in app/views/rounds/show.html.erb</p>

<%= flash[:notice] %>

<p>Tournament: <%= flash[:tournament_name] %></p>
<p>Name: <%= @round.name %></p>
<p>Round type: <%= @round.round_type %></p>
<p>Order: <%= @round.order %></p>