config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'persons/profile', as: 'user_root' 

  get 'admins', to: 'admins#index'

  get 'teams/search', to: 'teams#search'
  get 'tournaments/search', to: 'tournaments#search'
  get 'users/search', to: 'users#search'

  resources :users, :tournaments, :teams, :matches, :rounds, :votings

  resources :tournaments do
    resources :rounds
  end

  resources :rounds do
    resources :matches
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :teams
  has_and_belongs_to_many :tournaments

  #validates :name, :surname, :email, :password, presence: true
  #validates :password, confirmation: true

  # scope :user_tournaments, ->(id) { select("tournaments.name AS tour_name,
  #   tournaments.status, tournaments.id AS tour_id").distinct.joins(:tournaments)
  # .where("users.id = #{id}") if id.present?}

  # scope :teams, ->(id) { select("teams.name AS team_name,
  #   teams.active, teams.id AS team_id").distinct
  # .joins("INNER JOIN teams ON teams.first_user_id = users.id OR
  #   teams.second_user_id = users.id")
  # .where("users.id = #{id}")
  # .order("teams.active DESC") if id.present?}

  # scope :search, ->(keyword) { select("users.id, users.name, users.surname, 
  # users.photo, teams.name AS team_name, teams.id AS team_id,
  # teams.active")
  #   .joins("LEFT OUTER JOIN teams ON (teams.first_user_id = users.id OR
  #   teams.second_user_id = users.id) AND teams.active = true")
  #   .where("upper(users.name) = upper('#{keyword}') OR 
  #     upper(users.surname) = upper('#{keyword}')") if keyword.present? }

  def self.search(keyword)
    @users = User.select("users.id, users.name, users.surname, 
  users.photo, teams.name AS team_name, teams.id AS team_id,
  teams.active")
    .joins("LEFT OUTER JOIN teams ON (teams.first_user_id = users.id OR
    teams.second_user_id = users.id) AND teams.active = true")
    .where("upper(users.name) = upper('#{keyword}') OR 
      upper(users.surname) = upper('#{keyword}')")
  end

  def self.tournaments(user_id)
    @tournaments = User.select("tournaments.name AS tour_name,
    tournaments.status, tournaments.id AS tour_id").distinct.joins(:tournaments)
  .where("users.id": user_id)
  end  

  def self.teams(user_id)
    @team = User.select("teams.name AS team_name,
    teams.active, teams.id AS team_id").distinct
  .joins("INNER JOIN teams ON teams.first_user_id = users.id OR
    teams.second_user_id = users.id")
  .where("users.id": user_id)
  .order("teams.active DESC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def show
    @user = User.find_by id: params[:id]
    if @user.nil?
      flash[:notice] = "User not found"
      render "index"
    end
    @tournament = User.tournaments params[:id]
    @team = User.teams params[:id]
  end

  def update
    @user = User.update params[:id], user_params    
    if @user.save
      redirect_to @user
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:notice] = ""
      redirect_to @user
    else
      flash[:notice] = "Something went wrong, try again"
      render "new"
    end
  end

  def search
    @users = User.search params[:user][:keyword]
    if @users.size == 0
      flash[:notice] = "Nothing found for query '#{params[:user][:keyword]}'"
    end
    render 'index'
  end

  def user_params
    params.require(:user).permit(:name, :surname, :email, :photo, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_display.html.erb
<% if !row.nil? %>
	<div class="row">
		<%= image_tag row.photo, :class => 'user_photo' %>
		<%= link_to "#{row.surname} #{row.name}", user_url(row.id) %>
		<% if !row.team_name.nil? %>
			Team "<%= link_to "#{row.team_name}", team_url(row.team_id) %>"
		<% else %>
			No current team
		<% end %>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<% @user = User.find params[:id] %>

<%= form_tag "/users/#{params[:id]}", method: "put" do %>
	<%= content_tag :div, :class => "form-group" do %>
		<%= label :user, :name %>
		<%= text_field :user, :name %>
	<% end %>
	<%= content_tag :div, :class => "form-group" do %>
		<%= label :user, :surname %>
		<%= text_field :user, :surname %>
	<% end %>
	<%= content_tag :div, :class => "form-group" do %>
		<%= label :user, :email %>
		<%= text_field :user, :email %>
	<% end %>
	<%= content_tag :div, :class => "form-group" do %>
		<%= label :user, :photo %>
		<%= text_field :user, :photo %>
	<% end %>
	<%= submit_tag "Save changes" %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<%= label :user, "Find user" %>
<%= form_tag users_search_url, method: 'get', :class => 'form-inline' do %>
	<%= content_tag :div, :class => 'form-group' do %>
		<%= text_field :user, :keyword, :placeholder => 'Type here keyword', :value => '' %>
	<% end %>
	<%= submit_tag "Find user" %>
<% end %>

<div class="feed">
<% if !@users.nil? && @users.size != 0 %>
	<% @users.each do |user| %>
		<%= render 'users/display', row: user %>
	<% end %>
<% else %>
	<div class="row">
		<%= flash[:notice] %>
	</div>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= flash[:notice] %>
<p>Fill the form below</p>

<% if defined? @user %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% end %>

<%= form_tag :users, method: "post" do %>
	<%= content_tag :div, :class => "form-group" do %>
		<%= label :user, :name %>
		<%= text_field :user, :name %>
	<% end %>
	<%= content_tag :div, :class => "form-group" do %>
		<%= label :user, :surname %>
		<%= text_field :user, :surname %>
	<% end %>
	<%= content_tag :div, :class => "form-group", :type => "email" do %>
		<%= label :user, :email %>
		<%= text_field :user, :email %>
	<% end %>
	<%= content_tag :div, :class => "form-group" do %>
		<%= label :user, :photo %>
		<%= text_field :user, :photo %>
	<% end %>
	<%= content_tag :div, :class => "form-group" do %>
		<%= label :user, :password %>
		<%= text_field :user, :password, :type => "password" %>
	<% end %>
	<%= content_tag :div, :class => "form-group" do %>
		<%= label :user, :password_conf %>
		<%= text_field :user, :password_confirmation, :type => "password" %>
	<% end %>
	<%= submit_tag "Register" %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<%= render 'shared/profile' %>