config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'persons/profile', as: 'user_root' 

  get 'admins', to: 'admins#index'

  get 'teams/search', to: 'teams#search'
  get 'tournaments/search', to: 'tournaments#search'
  get 'users/search', to: 'users#search'

  resources :users, :tournaments, :teams, :matches, :rounds, :votings

  resources :tournaments do
    resources :rounds
  end

  resources :rounds do
    resources :matches
  end

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :rounds
  has_and_belongs_to_many :teams
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def show
    @tournament = Tournament.find_by id: params[:id]
    if @tournament.nil?
      flash[:notice] = "Tournament not found"
      render "index"
    end
  end

  def create
    @tournament = Tournament.new tournament_params
    if @tournament.save
      flash[:notice] = ""
      redirect_to @tournament
    else
      flash[:notice] = "Something went wrong, try again"
      render "new"
    end
  end

  def update
    #@tournament=Tournament.update(params[:id],:name => params[:tournament][:name], :status => params[:tournament][:status])
    @tournament = Tournament.update params[:id], tournament_params
    if @tournament.save
      flash[:notice] = "Changes saved"
      redirect_to @tournament
    else
      flash[:notice] = "Something went wrong, try again"
      render "edit"
    end
  end

  def tournament_params
    params.require(:tournament).permit(:name, :status)
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/edit.html.erb
<h1>Tournaments#edit</h1>
<p>Find me in app/views/tournaments/edit.html.erb</p>

<% @tournament = Tournament.find_by id: params[:id] %>

<%= flash[:notice] %>

<%= form_tag "/tournaments/#{params[:id]}", method: 'put' do %>
	<%= content_tag :div, :class => 'form-group' do %>
		<%= label :tournament,:name %>
		<%= text_field :tournament, :name %>
	<% end %>
	<%= content_tag :div, :class => 'form-group' do %>
		<%= label :tournament, :status %>
		<%= text_field :tournament, :status %>
	<% end %>
	<%= submit_tag "Save changes", class: 'btn btn-default' %>
<% end %>

<%= link_to 'Add rounds', new_tournament_round_path(params[:id]), class: "btn btn-default" %>

app/views/tournaments/index.erb
<h1>Tournaments#index</h1>
<p>Find me in app/views/tournaments/index.html.erb</p>

<%= flash[:notice] %>
<% flash[:notice] = "" %>

app/views/tournaments/new.html.erb
<h1>Tournaments#new</h1>
<p>Find me in app/views/tournaments/new.html.erb</p>


<%= form_tag :tournaments, method: "post" do %>
	<%= content_tag :div, :class => 'form-group' do %>
		<%= label :tournament, :name %>
		<%= text_field :tournament, :name %>
	<% end %>
	<%= content_tag :div, :class => 'form-group' do %>
		<%= label :tournament, :status %>
		<%= text_field :tournament, :status %>
	<% end %>
	<%= submit_tag "Create new tournament" %>
<% end %>

app/views/tournaments/show.html.erb
<h1>Tournaments#show</h1>
<p>Find me in app/views/tournaments/show.html.erb</p>

<p><%= flash[:notice] %></p>

<p>Name: <%= @tournament.name %></p>
<p>Status: <%= @tournament.status %></p>