config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'persons/profile', as: 'user_root' 

  get 'admins', to: 'admins#index'

  get 'teams/search', to: 'teams#search'
  get 'tournaments/search', to: 'tournaments#search'
  get 'users/search', to: 'users#search'

  resources :users, :tournaments, :teams, :matches, :rounds, :votings

  resources :tournaments do
    resources :rounds
  end

  resources :rounds do
    resources :matches
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, 
  :omniauthable
end

app/models/match.rb
class Match < ActiveRecord::Base
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :tournament
  has_many :teams
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :matches
  has_many :users
  has_and_belongs_to_many :tournaments

  scope :search, ->(keyword) { select("teams.id, teams.first_user_id,
    teams.second_user_id, teams.name AS team_name, teams.active, users.name, 
    users.surname")
    .joins("INNER JOIN users ON
    users.id = teams.first_user_id OR users.id = teams.second_user_id
    WHERE teams.name = '#{keyword}' OR users.name = '#{keyword}' OR
    users.surname = '#{keyword}'") if keyword.present? }

  scope :find_team, ->(id) { select("teams.name AS team_name, teams.active, 
    users.name, users.surname, users.photo, users.id AS user_id")
    .joins("INNER JOIN users ON
    users.id = teams.first_user_id OR users.id = teams.second_user_id
    WHERE teams.id = #{id}") if id.present? }

  scope :team_info, ->(id) { select("tournaments.id AS tour_id, 
    tournaments.name, tournaments.status")
    .joins(:tournaments).distinct if id.present?}

  scope :user_teams, ->(id) { select("teams.name AS team_name,
    teams.active, teams.id AS team_id")
  .joins("INNER JOIN users ON teams.first_user_id = users.id OR
    teams.second_user_id = users.id")
    .where("users.id = #{id}")
    .order("teams.active DESC") if id.present? }

  #scope :order_by_active, -> { order("teams.active DESC") }
end

# , tournaments.name
# .joins(:tournaments)

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :rounds
  has_and_belongs_to_many :teams
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :teams
  has_and_belongs_to_many :tournaments

  #validates :name, :surname, :email, :password, presence: true
  #validates :password, confirmation: true

  # scope :user_tournaments, ->(id) { select("tournaments.name AS tour_name,
  #   tournaments.status, tournaments.id AS tour_id").distinct.joins(:tournaments)
  # .where("users.id = #{id}") if id.present?}

  # scope :teams, ->(id) { select("teams.name AS team_name,
  #   teams.active, teams.id AS team_id").distinct
  # .joins("INNER JOIN teams ON teams.first_user_id = users.id OR
  #   teams.second_user_id = users.id")
  # .where("users.id = #{id}")
  # .order("teams.active DESC") if id.present?}

  # scope :search, ->(keyword) { select("users.id, users.name, users.surname, 
  # users.photo, teams.name AS team_name, teams.id AS team_id,
  # teams.active")
  #   .joins("LEFT OUTER JOIN teams ON (teams.first_user_id = users.id OR
  #   teams.second_user_id = users.id) AND teams.active = true")
  #   .where("upper(users.name) = upper('#{keyword}') OR 
  #     upper(users.surname) = upper('#{keyword}')") if keyword.present? }

  def self.search(keyword)
    @users = User.select("users.id, users.name, users.surname, 
  users.photo, teams.name AS team_name, teams.id AS team_id,
  teams.active")
    .joins("LEFT OUTER JOIN teams ON (teams.first_user_id = users.id OR
    teams.second_user_id = users.id) AND teams.active = true")
    .where("upper(users.name) = upper('#{keyword}') OR 
      upper(users.surname) = upper('#{keyword}')")
  end

  def self.tournaments(user_id)
    @tournaments = User.select("tournaments.name AS tour_name,
    tournaments.status, tournaments.id AS tour_id").distinct.joins(:tournaments)
  .where("users.id": user_id)
  end  

  def self.teams(user_id)
    @team = User.select("teams.name AS team_name,
    teams.active, teams.id AS team_id").distinct
  .joins("INNER JOIN teams ON teams.first_user_id = users.id OR
    teams.second_user_id = users.id")
  .where("users.id": user_id)
  .order("teams.active DESC")
  end
end

app/models/voting.rb
class Voting < ActiveRecord::Base
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def create
    @round=Round.new round_params
    if @round.save
      flash[:notice] = ""
      redirect_to @round
    else
      flash[:notice] = "Something went wrong, try again"
      render "new"
    end
  end

  def show
    @round = Round.find_by id: params[:id]
    if @round.nil?
      flash[:notice] = "Round not found"
      render "index"
    end
    flash[:tournament_name] = Tournament.find_by(id: @round.tournament_id).name
  end

  def update
    #@round=Round.update(params[:id],:name => params[:round][:name], 
    #  :round_type => params[:round][:round_type], :order => params[:round][:order])
    @round = Round.update params[:id], round_params
    if @round.save
      flash[:notice] = "Changes saved"
      redirect_to @round
    else
      flash[:notice] = "Something went wrong, try again"
      render "edit"
    end
  end

  def round_params
    params.require(:round).permit(:tournament_id, :name, :round_type, :order)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def show
    @team = Team.find_by id: params[:id]
    flash[:notice] = ''
    if @team.nil?
      flash[:notice] = "Team '#{params[:id]}' not found"
      render 'index'
    end
  end

  def create
    @team = Team.new team_params
    if @team.save
      flash[:notice] = ""
      redirect_to @team
    else
      flash[:notice] = "Something went wrong, try again"
      render 'new'
    end
  end

  def update
    @team = Team.update params[:id], team_params
    if @team.save
      flash[:notice] = "Changes saved"
      redirect_to @team
    else
      flash[:notice] = "Something went wrong, try again"
      render "edit"
    end
  end

  def search
    @team = Team.search params[:team][:keyword]
    if @team.size == 0
      flash[:notice] = "Nothing found for query '#{params[:team][:keyword]}'"
    end
    render 'index'
  end

  def team_params
    params.require(:team).permit(:first_user_id, :second_user_id, :name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def show
    @user = User.find_by id: params[:id]
    if @user.nil?
      flash[:notice] = "User not found"
      render "index"
    end
    @tournament = User.tournaments params[:id]
    @team = User.teams params[:id]
  end

  def update
    @user = User.update params[:id], user_params    
    if @user.save
      redirect_to @user
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:notice] = ""
      redirect_to @user
    else
      flash[:notice] = "Something went wrong, try again"
      render "new"
    end
  end

  def search
    @users = User.search params[:user][:keyword]
    if @users.size == 0
      flash[:notice] = "Nothing found for query '#{params[:user][:keyword]}'"
    end
    render 'index'
  end

  def user_params
    params.require(:user).permit(:name, :surname, :email, :photo, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/voting_helper.rb
module VotingHelper
end

app/views/admins/index.html.erb
<p>Admins#index</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag  	 'boostrap,min' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="container">
		<%= render 'shared/menu' %>
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/pages/index.html.erb
<h1>This is main page</h1>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
      	<img alt="Light IT football" src="light_it_logo.png">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if params[:controller] == 'pages' %>"><a href="/">Main</a></li>
          <li class="<%= 'active' if params[:controller] == 'persons' %>"><a href="/persons/profile" id="profile">Profile<span class="sr-only">(current)</span></a></li>
          <li  class="<%= 'active' if params[:controller] == 'tournaments' %>"><a href="/tournaments">Tournaments</a></li>
          <li  class="<%= 'active' if params[:controller] == 'teams' %>"><a href="/teams">Teams</a></li>
          <li  class="<%= 'active' if params[:controller] == 'users' %>"><a href="/users">Users</a></li>
          <% if current_user.admin? %>
            <li  class="<%= 'active' if params[:controller] == 'admins' %>"><a href="/admins">Admin panel</a></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li ><span class="navbar-text">Здравствуйте, <%= current_user.email %>, <%= current_user.surname %> <%= current_user.name.to_s.first %>.</span></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if params[:controller] == 'pages' %>"><a href="/">Main</a></li>
          <li class="<%= 'active' if params[:controller] == 'tournaments' %>"><a href="/tournaments">Tournaments</a></li>
          <li class="<%= 'active' if params[:controller] == 'teams' %>"><a href="/teams">Teams</a></li>
          <li class="<%= 'active' if params[:controller] == 'users' %>"><a href="/users">Users</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sign in <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">via vkontakte</a></li>
              <li><a href="#">via facebook</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Log in', new_user_session_path %></li>
              <li>
                <form class="navbar-form form-horizontal">
                  <label>via email</label>
                  <div class="form-group">
                    <input type="text" class="form-control" placeholder="Email">
                    <input type="password" class="form-control" placeholder="Password">
                  </div>
                  <button type="submit" class="btn btn-default">Submit</button>
                </form>
              </li>
            </ul>
          </li>
          <li><%= link_to 'Sing up', new_user_registration_path %></li>
<!--           <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sign up <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">via vkontakte</a></li>
              <li><a href="#">via facebook</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="/users/new">via email</a></li>
            </ul>
          </li> -->
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_profile.html.erb
<div id=row1>
	<h3>User info  
		<% if params[:controller] == 'persons' || current_user.id == @user.id %>
			<%= link_to 'edit', edit_user_url(@user.id) %>
		<% end %>
	</h3>
	<div id="photo">
		<%= image_tag @user.photo, :class => 'user_photo' %>
	</div>
	<div id="info">
		<table>
		<tr>
			<th>Name</th><td><%= @user.name %></td>
		</tr>
		<tr>
			<th>Surname</th><td><%= @user.surname %></td>
		</tr>
		<tr>
			<th>Email</th><td><%= @user.email %></td>
		</tr>
		</table>
	</div>
	<div class="clear"></div>
</div>
<div id="row2">
	<h3>Activity</h3>
	<div id="tour">
			<% _tour = @tournament %>
			<% if _tour.size == 0 %>
				<h3>No tournaments yet</h3>
			<% else %>
				<h3>Current tournaments:</h3>
				<% if (_active = _tour.where(tournaments: {status: "active"})).size == 0 %>
					<p>No tournamnets yet</p>
				<% else %>
					<% _active.each do |row| %>
						<p><%= link_to row.tour_name, tournament_url(row.tour_id) %></p>
					<% end %>
				<% end %>

				<h3>Passed tournaments:</h3>
				<% if (_passed = _tour.where(tournaments: {status: "inactive"})).size == 0 %>
					<p>No tournamnets yet</p>
				<% else %>
					<% _passed.each do |row| %>
						<p><%= link_to row.tour_name, tournament_url(row.tour_id) %></p>
					<% end %>
				<% end %>
			<% end %>
	</div>
	<div id="team">
		<% if @team.size == 0 %>
			<h3>No teams yet</h3>
		<% else %>
			<h3>Current team:</h3>
			<% if (_active = @team.where(teams: {active: 'true'})).size == 0 %>
				<p>No teams yet</p>
			<% else %>
				<% _active.each do |row| %>
					<p><%= link_to row.team_name, team_url(row.team_id) %></p>
				<% end %>
			<% end %>

			<h3>Previous teams:</h3>
			<% if (_passed = @team.where(teams: {active: 'false'})).size == 0 %>
				<p>No teams yet</p>
			<% else %>
				<% _passed.each do |row| %>
					<p><%= link_to row.team_name, team_url(row.team_id) %></p>
				<% end %>
			<% end %>
		<% end %>
	</div>
</div>